Scrum 4 signup page
mentorbridgeindia/securosphere pull request #7
Opened 2024-12-12 11:29 UTC by JEYASHREESELVAN

## JIRA User story link

https://mentorbridgeindia.atlassian.net/browse/SCRUM-4?atlOrigin=eyJpIjoiMmNiMzcyMmFkMDhkNDJhNjk4YTZjOTExNWI0MGU0ZWEiLCJwIjoiaiJ9

### Explain What was done in this change
create a sign up page and add validation part ,made alignment and adding style
_________________
#### PR Checklist
- [ ] No lining, TS, or console errors
- [ ] No commented-out code without a reason
- [ ] No business logic inside UI components
- [ ] Dev tests are done: all the related components are working as before

2024-12-20 17:23 UTC, mentorbridgeindia requested changes

2024-12-20 17:23 UTC, mentorbridgeindia commented on .vscode/settings.json
Remove .vscode related files

2024-12-20 17:23 UTC, mentorbridgeindia commented on src/pages/Regi.css
Give name properly like Register.scss

2024-12-20 17:23 UTC, mentorbridgeindia commented on src/pages/Register.tsx
> +import { FormLabel } from '@/ui/atoms/FormLabel';
@atoms/FormLabel

2024-12-20 17:23 UTC, mentorbridgeindia commented on src/pages/Register.tsx
> +import { FormInput } from '@/ui/atoms/FormInput';
@atoms/FormInput

2024-12-20 17:23 UTC, mentorbridgeindia commented on src/pages/Register.tsx
> +import { Anchor } from '@/ui/atoms/Anchor';
@atoms/Anchor

2024-12-20 17:23 UTC, mentorbridgeindia commented on src/pages/Register.tsx
> +            className={`d-flex justify-content-center align-items-center ${Object.keys(errors).length > 0 ? 'mt-5' : 'mt-4'
Create a class in Register.scss and use it here

2024-12-20 17:23 UTC, mentorbridgeindia commented on public/google.jpg
If you are using svg, then remove this file

2024-12-20 17:23 UTC, mentorbridgeindia commented on public/signup.jpeg
If you are using svg, then remove this file

2024-12-20 17:23 UTC, mentorbridgeindia commented on public/linkedin.jpg
If you are using svg, then remove this file

2024-12-20 17:23 UTC, mentorbridgeindia commented on src/pages/Register.tsx
> +                                    <svg
Move this svg to a seperate file and name icon-google.svg and place it under src/assets/icons

2024-12-20 17:23 UTC, mentorbridgeindia commented on src/pages/Register.tsx
> +                                    <svg
Move this svg to a separate file and name icon-github.svg and place it under src/assets/icons

2024-12-20 17:23 UTC, mentorbridgeindia commented on src/pages/Register.tsx
> +                                    <svg
Move this svg to a separate file and name icon-linked.svg and place it under src/assets/icons

2024-12-20 17:23 UTC, mentorbridgeindia commented on src/pages/Register.tsx
> +                            <Row>
Create a module named RegisterForm under modules folder and put this form there

2024-12-28 09:17 UTC, JEYASHREESELVAN commented on src/pages/Regi.css
I'm not using Regi.css file  .i'm using only bootstrap . if  will needed i use scss file

2024-12-28 09:18 UTC, JEYASHREESELVAN commented on src/pages/Register.tsx
> +import { FormLabel } from '@/ui/atoms/FormLabel';
yes  sir

2024-12-28 09:18 UTC, JEYASHREESELVAN commented on src/pages/Register.tsx
> +import { FormInput } from '@/ui/atoms/FormInput';
yes sir

2024-12-28 09:18 UTC, JEYASHREESELVAN commented on src/pages/Register.tsx
> +import { Anchor } from '@/ui/atoms/Anchor';
ok sir

2024-12-31 15:42 UTC, closed without merging