Scrum 35 create organization config page
mentorbridgeindia/securosphere pull request #8
Opened 2024-12-13 04:10 UTC by Vishnu17092003

## JIRA User story link

### Explain What was done in this change

_________________

#### PR Checklist
- [ ] No lining, TS, or console errors
- [ ] No commented-out code without a reason
- [ ] No business logic inside UI components
- [ ] Dev tests are done: all the related components are working as before

2024-12-13 04:13 UTC, Vishnu17092003 commented
Completed the first story

2024-12-13 05:46 UTC, mentorbridgeindia requested changes

2024-12-13 05:46 UTC, mentorbridgeindia commented on public/form1.png
Is this needed?

2024-12-13 05:46 UTC, mentorbridgeindia commented on src/pages/OrgPage.tsx
> +  oname: yup
orgName

2024-12-13 05:46 UTC, mentorbridgeindia commented on src/pages/OrgPage.tsx
> +  ecount: yup
empCount

2024-12-13 05:46 UTC, mentorbridgeindia commented on src/pages/OrgPage.tsx
> +    web: yup
website

2024-12-14 06:43 UTC, mentorbridgeindia commented
> ## JIRA User story link
> ### Explain What was done in this change
> #### PR Checklist
> * [x]  No lining, TS, or console errors
> * [x]  No commented-out code without a reason
> * [x]  No business logic inside UI components
> * [x]  Dev tests are done: all the related components are working as before

Where are the details?

2024-12-31 15:42 UTC, closed without merging